version: '3'
services:

  mysql-server:
    image: mysql:5.7.21
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
    ports:
      - 3307:3306
    volumes:
      - './.data/mysql:/var/lib/mysql'

  mongo-server:
    image: 'mongo:4.0'
    container_name: mongo-server
    ports:
      - '27017:27017'
    volumes:
      - './.data/mongo:/data/db'
      - './.data/mongoconfigdb:/data/configdb'

  # Server
  backend-service:
    container_name: backend-service
    build:
      context: .
      dockerfile: .Dockerfile
    command: 'npm run debug'
    ports:
      - '3001:3001'
      - '9229:9229'
    volumes:
      - ./:/app
      - '/app/node_modules'
    depends_on:
      - mysql-server
      - mongo-server
